---
abstract: 'Create and manipulate time widgets.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Curses-UI-Time
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Curses::UI: 0
  Curses::UI::Number: 0
  Readonly: 0
  Unicode::UTF8: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Curses-UI-Time
  homepage: https://github.com/michal-josef-spacek/Curses-UI-Time
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Curses-UI-Time
version: '0.07'
