---
abstract: TODO
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Curses-UI-Time
no_index:
  directory:
    - examples
    - inc
    - t
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Curses-UI-Time
  homepage: https://github.com/tupinek/Curses-UI-Time
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Curses-UI-Time
version: 0.01
